### ISSUE TITLE
package.json has a backslash in the "main" property.

### ISSUE THREAD

**Issue by hhamilto** [stevecooperorg/canto34#1]
Excerpt from package.json:
```
{
  "name": "canto34",
  "version": "0.0.3",
  "description": "A library for helping you build recursive descent parsers and regex-based lexers",
  "main": "src\\canto34.js",
  "directories": {
  "doc": "docs",
...
```
The "main" property has a windows backslash in it, which makes the module un-loadable on *nix machines.

I'll create a fork and see if I can come up with a fix, because I'm curious about your lexer. 

Cheers!

**Comment by stevecooperorg** [comment]
Thanks! good spot :) let me know how you get on.

Steve Cooper
steve@stevecooper.org
http://www.stevecooper.org

**Comment by stevecooperorg** [comment]
Now fixed. Thanks for the heads-up

**Comment by hhamilto** [comment]
Cheers! Thanks again for this project.
